use std::collections::HashMap;

lazy_static::lazy_static! {
    pub static ref ROULETTES: HashMap<u32, &'static str> = maplit::hashmap! {
        1 => "Duty Roulette: Leveling",
        2 => "Duty Roulette: Level 50/60/70 Dungeons",
        3 => "Duty Roulette: Main Scenario",
        4 => "Duty Roulette: Guildhests",
        5 => "Duty Roulette: Expert",
        6 => "Duty Roulette: Trials",
        7 => "Daily Challenge: Frontline",
        8 => "Duty Roulette: Level 80 Dungeons",
        9 => "Duty Roulette: Mentor",
        11 => "The Feast (Training Match)",
        13 => "The Feast (Ranked Match)",
        15 => "Duty Roulette: Alliance Raids",
        16 => "The Feast (Team Ranked Match)",
        17 => "Duty Roulette: Normal Raids",
        18 => "Chocobo Race: Sagolii Road",
        19 => "Chocobo Race: Costa del Sol",
        20 => "Chocobo Race: Tranquil Paths",
        21 => "Chocobo Race: Random",
        22 => "Chocobo Race: Sagolii Road (No Rewards)",
        23 => "Chocobo Race: Costa del Sol (No Rewards)",
        24 => "Chocobo Race: Tranquil Paths (No Rewards)",
        25 => "Chocobo Race: Random (No Rewards)",
        26 => "Chocobo Race: Random",
        27 => "Chocobo Race: Random",
        28 => "Chocobo Race: Random",
        29 => "Chocobo Race: Random",
        30 => "Chocobo Race: Random",
        31 => "Chocobo Race: Random",
        32 => "Chocobo Race: Random",
        33 => "Chocobo Race: Random",
        34 => "Chocobo Race: Random",
        35 => "Chocobo Race: Random",
        36 => "Chocobo Race: Random",
        37 => "Chocobo Race: Random",
        38 => "Chocobo Race: Random",
    };
}
